# Generated by Django 5.0.6 on 2024-08-31 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="registration_method",
            field=models.CharField(
                blank=True, default="Email_password", max_length=50, null=True
            ),
        ),
    ]
