# Generated by Django 5.0.6 on 2024-09-02 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_customuser_registration_method"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BusinessCategogy",
            new_name="BusinessCategory",
        ),
    ]
